const data = {
  products: [
    {
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (1).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      name: 'golfer shirt',
      category: 'shirts',
      image: 'images/golfer (2).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      name: 'Botta shirt',
      category: 'shirts',
      image: 'images/golfer (3).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      name: 'Alien golfer shirt',
      category: 'shirts',
      image: 'images/golfer (4).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      name: 'Golf golfer shirt',
      category: 'shirts',
      image: 'images/golfer (5).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (6).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (7).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (8).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (9).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (10).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (11).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (12).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (13).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (14).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
  ],
};

export default data;
