const data = {
  products: [
    {
      id: 1,
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (1).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      id: 2,
      name: 'golfer shirt',
      category: 'shirts',
      image: 'images/golfer (2).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      id: 3,
      name: 'Botta shirt',
      category: 'shirts',
      image: 'images/golfer (3).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      id: 4,
      name: 'Alien golfer shirt',
      category: 'shirts',
      image: 'images/golfer (4).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      id: 5,
      name: 'Golf golfer shirt',
      category: 'shirts',
      image: 'images/golfer (5).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      id: 6,
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (6).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      id: 7,

      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (7).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      id: 8,
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (8).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      id: 9,
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (9).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      id: 10,
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (10).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      id: 11,
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (11).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      id: 12,
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (12).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      id: 13,
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (13).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
    {
      id: 14,
      name: 'francis golfer shirt',
      category: 'shirts',
      image: 'images/golfer (14).jpeg',
      price: '$120',
      brand: 'Golfer',
      sex: 'men',
    },
  ],
};

export default data;
