import '../scss/App.scss';
import store from '../redux/store';
import { Provider } from 'react-redux';
import Layout from '../Components/Layout';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <Provider store={store}>
      <Head>
        <title>Francis Golfer | welcome to francis golfer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./BBK.png" />
      </Head>
      <Layout>
        <Component {...pageProps} />;
      </Layout>
    </Provider>
  );
}

export default MyApp;
