import Head from 'next/head';
import SectionThree from '../Components/SectionThree';
import SectionOne from '../Components/SectionOne';
import SectionTwo from '../Components/SectionTwo';
import Layout from '../Components/Layout';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Francis Golfer | welcome to francis golfer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        <div className="Home">
          <div className="Home__section--one">
            <SectionOne />
            <div className="Home__section--two">
              <SectionTwo />
            </div>
            <div className="Home__section--three">
              <SectionThree />
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
}
